### ISSUE TITLE
Extend Technological Overview

### ISSUE THREAD

**Issue by beheist** [neos/documentation#10]
https://docs.neos.io/cms/manual/technological-overview should be extended.
To me, this is the biggest issue with the current docs. We explain the individual technologies (Fusion, Fluid, Eel, FlowQuery, Config, NodeTypes, …) pretty well. But there is no point where we explain how the whole thing fits together, and this is also why newbies get confused so quickly. They simply cannot build a mental model of Neos that allows them to understand what Fusion/Fluid/whatever actually does, and why. The Technical Principles 2 section of the docs is empty - this speaks for itself.

**Comment by skurfuerst** [comment]
@maxstoyanov I've started with this; see https://docs.neos.io/cms/manual/technological-overview . I think we can from time to time revisit this page and deepen it; but I'd say for now it's perfectly fine to keep it this way.

I'd close this issue, WDYT?

**Comment by maxstoyanov** [comment]
According to the Pareto Principle we're mostly there. So i'll close.
