### ISSUE TITLE
Remove the "User Guide"

### ISSUE THREAD

**Issue by beheist** [neos/documentation#11]
https://neos.readthedocs.io/en/stable/UserGuide/index.html
as we have a very good one on neos.io now: https://www.neos.io/docs-and-support/editor-documentation.html

**Comment by rolandschuetz** [comment]
So this is a bug in this PR
https://github.com/neos/neos-development-collection/pull/2112

**Comment by beheist** [comment]
I'll do this if you're fine with it @kdambekalns ?

**Comment by beheist** [comment]
Ah, just saw it's already gone on master. nvm then ;)

**Comment by kdambekalns** [comment]
No, it's not done. As long as it's in the old versions, we cannot redirect (properly). I'm at it, as per "assigned" in this issue…

**Comment by kdambekalns** [comment]
@beheist see PR. As soon as that is (up)merged, and redirects are in place this is done

**Comment by kdambekalns** [comment]
✅ I have now added the redirects for the removed pages.

**Comment by kdambekalns** [comment]
Note: "stable" is 4.1.8 and (as any tagged version) will continue to have the removed content.
