### ISSUE TITLE
Add Best Practices

### ISSUE THREAD

**Issue by beheist** [neos/documentation#13]
The best practices are on the official blog but should also be in our manual: https://www.neos.io/blog/neos-best-practices-1-0.html

This is a simple copy and paste task.

**Comment by rolandschuetz** [comment]
We decided on best practices at the Salzburg sprint. I will write them down in the docs and as a blog post.

**Comment by rolandschuetz** [comment]
I integrated them in the docs.https://docs.neos.io/cms/manual/best-practices

The more relevant part is to actually follow them in all our docs. I have rewritten all NodeType code examples to match them. Will do the same for Fusion soon.
