### ISSUE TITLE
Write "Extending the Neos UI"

### ISSUE THREAD

**Issue by beheist** [neos/documentation#16]
React UI docs are kinda spread out currently.
The entire UI section 1 is outdated, there is still some Ember stuff in there, and some of it is just plain wrong by now. On the other hand, there is some React UI documentation spread over several chapters (such as https://neos.readthedocs.io/en/stable/ExtendingNeos/CustomEditors.html and https://neos.readthedocs.io/en/stable/Contribute/Code/UI.html and also https://github.com/neos/neos-ui) which needs to be cleaned up. And of course, there is a lot of information missing on how to get started with extending the UI.

**Comment by rolandschuetz** [comment]
The docs now clearly differentiate between legacy and up to date React. All content relevant is moved to this chapter. 
https://docs.neos.io/cms/manual/extending-the-user-interface
