### ISSUE TITLE
Examples of good docs structure

### ISSUE THREAD

**Issue by beheist** [neos/documentation#2]
Just starting an unstructured collection of docs where I like certain aspects - please add yours.

Kubernetes docs: I like that they have an extra section "Concepts", which explains the basic terms to make sense of the rest of the docs.
![image](https://user-images.githubusercontent.com/10347669/46143216-9d325700-c259-11e8-883d-1bf0d3e7c150.png)

**Comment by beheist** [comment]
What I like especially here is that they explain each concept in terms of the problems it solves. Here's an example for Services:
![image](https://user-images.githubusercontent.com/10347669/46147365-a1647180-c265-11e8-960d-d2bb814fb37e.png)

**Comment by mstruebing** [comment]
To just throw that in: https://hexdocs.pm/phoenix/Phoenix.html
Phoenixframework docs are often praised as nice and complete docs.
I missed the disscussion around that topic sorry, but I think they are worth to look at.

What I like about them: they have a step by step guide which does everything a newcomer would do but also complete references.

**Comment by chkoeppel** [comment]
The following Docs/Tutorials caught my attention today

> **Digital Ocean**  (= American cloud platform provider)

- there is the **global** 'Docs' overview [Digital Ocean](https://www.digitalocean.com/docs/)
  see the structured menu on the left (kind of **global segmentation** of the whole Docs-Space)

- the **interesting thing** is their complementary '**functional**' section for [Tutorials 'Digital Oceans'](https://www.digitalocean.com/community/tutorials)

The **tutorial implementation** basically shows how sophisticated things become with a lean design and some handy and fast filters ...

- when you **enter now into a topic**, you can see the internal '**contentStructure**' and the 'feedback/rating' buttons ...
- furthermore you see the '**contributingButton**' on top ...
 
**Especially** concerning the '**content structure**', - we have the ability in **Neos** to deliver some '**typical content types**' (nodetypes) which will keep design standards and **help/animate** the contributor to edit chapters in a structured and completing manner ...

I think this covers already a lot of what we are heading for, concerning the **tutorial 'dynamics'** ... ?

Another "**Tutorial**-Gate", that I found ... (to compare filters, design, etc)

- https://tutorials.ubuntu.com/

... interesting to compare with theirs (very **conceptual**) docsOverviews
- https://docs.ubuntu.com/
- https://www.debian.org/doc/

Finally a link that **Karsten** mentioned on Slack ... (GitHub **Learning Lab for organizations**)
- https://lab.github.com/organizations

**Comment by maxstoyanov** [comment]
Since we're out of the design phase for our new docs I'll close this
