### ISSUE TITLE
Update Custom Backend Modules

### ISSUE THREAD

**Issue by beheist** [neos/documentation#21]
We have had this feature for ages and it works perfectly, but there is no official documentation on how to create a custom backend module.

**Comment by beheist** [comment]
Hah, that's actually not true. We have documentation for that, but it can be improved a bit ;)
https://neos.readthedocs.io/en/stable/ExtendingNeos/CustomBackendModules.html

**Comment by maxstoyanov** [comment]
We already have the old docs in our new system: https://docs.neos.io/cms/manual/using-neos-with-php-flow/custom-backend-modules

What can be updated and what is missing?

**Comment by rolandschuetz** [comment]
Slightly updated version is at:
https://docs.neos.io/cms/manual/using-neos-with-php-flow/custom-backend-modules

Of course, this can be improved like many pages. But let's keep the state the Neos docs via tags.
