### ISSUE TITLE
Clean up ReadTheDocs

### ISSUE THREAD

**Issue by rolandschuetz** [neos/documentation#22]
Remove everything from RTD except reference-style pages and content that should be versioned with Git.

These need to stay in the docs:
https://neos.readthedocs.io/en/stable/ExtendingNeos/Tests/Behat.html (should be moved to contribute)
https://neos.readthedocs.io/en/stable/ExtendingNeos/UiExtensibility.html
https://neos.readthedocs.io/en/stable/Operations/CommandLine.html
https://neos.readthedocs.io/en/stable/References/index.html plus all subpages
https://neos.readthedocs.io/en/stable/InsideOfNeos/index.html plus  all subpages (through mostly outdated)

**Comment by maxstoyanov** [comment]
I'd say we remove Inside of Neos also. It's mostly outdated.

**Comment by rolandschuetz** [comment]
See https://github.com/neos/neos-development-collection/pull/2616
