### ISSUE TITLE
How to gather user feedback

### ISSUE THREAD

**Issue by maxstoyanov** [neos/documentation#25]
We will definetly need feedback from real users. An important aspect of feedback systems is conveying relevance of the given feedback.

How do we want to handle feeback? Where does it go? How do we handle this on the technical side of things?

Possible tools:
- [usabilla.com](https://usabilla.com/)

**Comment by skurfuerst** [comment]
Hey @maxstoyanov ,

I'd suggest we move this priority-wise to "Medium"; i.e. I'd suggest to work on this as soon as the the docs as they are online are OK :) 

All the best,
Sebastian

**Comment by maxstoyanov** [comment]
My rationale is this: As soon as we tell the world that we've got new docs we'll have a lot of people looking at them and I want to take this momentum and gather questions and feedback as a basis for improving them.

**Comment by rolandschuetz** [comment]
Most of the guys voted for keeping it in Slack and Email. So we have those now.
