### ISSUE TITLE
Video transcripts for Getting Started

### ISSUE THREAD

**Issue by maxstoyanov** [neos/documentation#28]
The Getting Started section only features videos but it need's the exact same content in text form.

- [ ] [Getting Started](https://docs.neos.io/cms/building-your-first-website)
- [ ] [Dependency Management](https://docs.neos.io/cms/building-your-first-website/dependency-management)
- [ ] [Local Setup](https://docs.neos.io/cms/building-your-first-website/local-setup)
- [ ] [What We Want to Build](https://docs.neos.io/cms/building-your-first-website/what-we-want-to-build)
- [ ] [Your First NodeType](https://docs.neos.io/cms/building-your-first-website/your-first-node-type)
- [ ] [Understanding Rendering](https://docs.neos.io/cms/building-your-first-website/understanding-rendering)
- [ ] [Frontend Design](https://docs.neos.io/cms/building-your-first-website/frontend-design)
- [ ] [Working with Images](https://docs.neos.io/cms/building-your-first-website/working-with-images)

@rolandschuetz Do you have text transcripts or notes that can be used as a basis?

**Comment by rolandschuetz** [comment]
No, I only had talking points. And I already added all links at the bottom of the video.

**Comment by rolandschuetz** [comment]
AI could help to transcribe the video with whisper and then let it re-write with ChatGPT. So it would probably be only one day of work...
