### ISSUE TITLE
Dual nature of Documentations ?

### ISSUE THREAD

**Issue by chkoeppel** [neos/documentation#3]
**Analysing** 'competitors' docs I tried to **break down** the overall topic to gain a "**_dual frame_**" where standard documentation should find its place ...
(https://www.divio.com/blog/documentation goes in this direction too, no ?)

I finally think that **2 complementary** frames would cover the Neos '**Docs-Space**'

1. a more **'conceptual' Frame** (= official approved, versioned docs) whose content stays **under the full authority of the Neos project** (as it is already now !!). There would be no change, just keep the standard and maintain and complete it over time ... 
2. a **'strategic' Frame** (where docs of '**dynamic**' nature would be ranged). Typically there would be tutorials, guides, etc (really quite 'atomic' docs) which would be elaborated by people that are not necessarily implied in the Neos-project, but would **share pieces of knowledge**, where the risk of 'imperfection' would be implied. There would be an official 'Disclaimer' and am implemented 'technical ruling' (filters and fundamental algorithms which would relativize this 'implicit imperfection' over time. 
(working example: https://www.digitalocean.com/community/tutorials )

To show what I mean, - hereafter the **2 complementary drafts** that would cover the Neos-disposition
![top-down disposition - google docs](https://user-images.githubusercontent.com/20425780/46690566-e3e16300-cc02-11e8-9090-304e2197e968.png)

![top-down disposition - google docs 1](https://user-images.githubusercontent.com/20425780/46690706-4cc8db00-cc03-11e8-856a-2fff1f72902e.png)

- see this rough draft **implementation with Neos** (to demonstrate the **_menu topology_** ...):  
  https://neosdocs.infoservicing.ch/de/static/project/neos-core.html

**Technically**, - to implement a 'Docs-EntryPoint' with the tool **Neos-CMS**

- the **'conceptual'** part would / could be a '**page-tree**' that references on the already existing official Neos docs ...  ?
(like seen in already discussed examples: implementing menu structure, links, design)

- the **'dynamic'** part would be technically **challenging** (functionality and design) but as we see, there are competitors who show us the way to go ... (conceptually)
(_**examples**_: 
https://www.digitalocean.com/community/tutorials
https://tutorials.ubuntu.com

To clarify, I'm defining above the global **FRAME** of 'the docs', - NOT the content ... 
This proposal/description could be a basis for our discussion
- what do we imagine to cover finally ...
- what technical solution are we heading for ...

If we **gain overview** on the beginning, we may be clear at the end ...
(even if we don't implement the whole circus at once ...)
_References:_
http://docs.django-cms.org/en/release-3.4.x/
https://docs.djangoproject.com/en/1.11/#how-the-documentation-is-organized
https://www.debian.org/doc/
https://kubernetes.io/docs/concepts/
https://hexdocs.pm/phoenix/Phoenix.html
https://learn-neos.com/blog/hitchhikers-guide-to-typoscript-2-part1.html
...

**Comment by chkoeppel** [comment]
>  To **summarize** the described theme above

Is this **basic combination** more or less the direction to go **...?**
1. a structured 'deep-wide-Top-Down' **overview** implementation to cover the whole 'documentation domain'
2. a 'dynamic' searchable section with intelligent ruling and filters to **find** 'user' doc-content 

To concretize the **idea**, here a **basic implementation draft** (for the **Neos** documentation context)
- https://neosdocs.infoservicing.ch

see **working example of companies** who obviously had to solve similar problems ...
- https://www.digitalocean.com/community/tutorials
- https://tutorials.ubuntu.com/
- https://kubernetes.io/docs/home/?path=users&persona=app-developer&level=foundational

**Comment by chkoeppel** [comment]
**Recapitulating** some **feedback** from a discussion on the Meetup in Zürich, concerning this 'concept'
1. When the **tutorial** link of 'DigitalOcean' was shown, somebody (who often visited their site apparently) mentioned that he would never have seen this 'Tutorial site' ...
(coming from Google search ? or https://www.digitalocean.com/docs/  ?)
(in this case of 'DigitalOcean', the 'tutorials' are part of '_Community_' and there is indeed **NO direct link** to these 'tutorials')
> **WHERE** are the documentations **located**
> - how to find them if I **do NOT** search for them
> - how to find them if I **DO** actively search for them (=**want** to find them)

2. Somebody pointed out that they had **videos** that they **wanted to share** ... 
(nowadays you will probably visit neos slack channel, and most probably Christian Müller, Johannes Steu or Soren Malling will pass you the right video link, - faster than google engines)
> IF somebody wants to **share** their tutorials, videos, howTos ... WHERE can these be LINKED ??

3. Presented the idea, that 'dynamic Docs' (tutorial, videos, howTos, ...) could be regulated by filters, - **it was pointed out** that sorting algorithm '**would never been fair**' ...
> the more of **complementary labels** (dates, rating, author, title, ...) are available (=implemented), - the dominance of each filter-option would decrease ... 
(finally, - the user himself takes responsibility of the filter priorities by his own choice)

**my Conclusion**
Instead of **delegating/spread out** the problem to engines like Stackoverflow, Google, ... an **adapted Docs-Structure** would permit to keep control over time ...
**Whenever** tutorials, videos, etc would have been generated, - there should at least exist an easy possibility to formally **reference them** in the docs library directory. (links, contentElements, ...) 
Nowadays it would cost probably more time to place (=share under Neos flag) a small tutorial, than to create it. (=frustrating ?)

**Comment by maxstoyanov** [comment]
Since we're out of the design phase for our new docs I'll close this
