### ISSUE TITLE
Combine, smoothen+finish "Structuring Content" + "NodeTypes"

### ISSUE THREAD

**Issue by skurfuerst** [neos/documentation#31]
Hey,

Both these pages are not finished at all, contain duplicate infos, do not tell a consistent story :)

https://docs.neos.io/cms/manual/content-repository/mapping-content-to-nodetypes
https://docs.neos.io/cms/manual/content-repository/nodetypes

All the best,
Sebastian

**Comment by maxstoyanov** [comment]
I'll be working this week on the whole Content Repository and Rendering chapters. Those are so close that one can not be explained without the other.

My process looks like this:

1. I think of someone who has no prior experience in structured content editing but knows web technologies.
2. I try to anticipate their questions and mental state of mind and introduce them to those topics.
3. I create a document that consists of nested lists. Those can be either pages, headings, bullet points and later serve as a writing strategy and thus enabling us to split the workload among the whole team.

(Loosely inspired by [Simplyfiying Complexity by Tom Johnson](https://idratherbewriting.com/simplifying-complexity/).)

**Comment by rolandschuetz** [comment]
I have combined the old docs with some existing skeletons and added a lot of content.

It's now split up in:
https://docs.neos.io/cms/manual/content-repository/data-structure (theory)
https://docs.neos.io/cms/manual/content-repository/presentational-or-semantic
https://docs.neos.io/cms/manual/content-repository/nodetype-definition (practical, followed by properties, constraitns, ...)

**Comment by skurfuerst** [comment]
awesome <3 <3 <3 :)
