### ISSUE TITLE
Create specific plan how the content in "Rendering" should be structured

### ISSUE THREAD

**Issue by skurfuerst** [neos/documentation#34]
We should create an outline how the content in https://docs.neos.io/cms/manual/rendering should be structured; and then create tickets to actually write this.

**Comment by maxstoyanov** [comment]
I'll be working this week on the whole Content Repository and Rendering chapters. Those are so close that one can not be explained without the other.

My process looks like this:

1. I think of someone who has no prior experience in structured content editing but knows web technologies.
2. I try to anticipate their questions and mental state of mind and introduce them to those topics.
3. I create a document that consists of nested lists. Those can be either pages, headings, bullet points and later serve as a writing strategy and thus enabling us to split the workload among the whole team.

(Loosely inspired by [Simplyfiying Complexity by Tom Johnson](https://idratherbewriting.com/simplifying-complexity/).)

**Comment by skurfuerst** [comment]
Awesome! Please ping me if you have detail questions, I'll be around for correctness checks etc :)
