### ISSUE TITLE
decide what to do with "Localization & Internationalization" chapter

### ISSUE THREAD

**Issue by skurfuerst** [neos/documentation#35]
the chapter https://docs.neos.io/cms/manual/localization is somehow a duplicate of https://docs.neos.io/cms/manual/content-repository/multiple-languages -> we should decide which one to keep (to me it makes more sense to keep it in the CR).

**Comment by rolandschuetz** [comment]
My idea is to use familiar words and then lead readers to the correct places. The chapter now only serves as a waypoint to the right chapters:
https://docs.neos.io/cms/manual/localization

**Comment by rolandschuetz** [comment]
Good? Can we close this?

**Comment by rolandschuetz** [comment]
Good? Can we close this?

**Comment by skurfuerst** [comment]
awesome <3
