### ISSUE TITLE
some User Feedbacks ...

### ISSUE THREAD

**Issue by chkoeppel** [neos/documentation#4]
https://discuss.neos.io/t/deep-top-down-documentation/3780
Thomas Martelo gives an example:

> There is no doc explaining the complete rendering process for a NEOS request. If I would understand what is happening there it would be quite easy to start developing. But from the current docs I never know my complete surrounding. I just see the next wall but not the room or even the house.
> More details, there is this graphic in the current documentation:
> ![grafik](https://user-images.githubusercontent.com/20425780/46760861-6fc2c000-ccd3-11e8-9767-d5a28bc2d29b.png)
> 
> - How does NEOS get the request and to which process is it forwarded?
> - When we are in a document node certain processes must have been finished. Which ones? Where am I in the rendering stack? What is my surrounding? Which objects of which system parts do I have access to? …
> - When I am in the fusion part same questions as above. So much must have been happened. It’s not only fusion that have to know at this time. I have to know where I am and to which objects or system parts I do have access.
> - Fluid of course same subject.
> - Documentation of Flow, Fusion, Fluid and so on is just a subpart.
> 
> This is just a small example but shall explain the blindness with which I’m walking through the NEOS complex. It is not possible for me to get this knowledge just by try and fail in an accetable time. And as I want to use the system for client projects I cannot just start and look how long it takes.

**Comment by chkoeppel** [comment]
**_Basic_** 'CMS' topics for somebody coming from outside and just wants to build a **_basic construct_**
- https://neos.readthedocs.io/en/stable/CreatingASite/index.html

1. **MENU**
how do work the '**menu**' mecanics
- example: where does come '**items**' from ? do I have to dive into the code 'MenuImplementation' to **get an idea** ... can I find compact information in the docs / tutorials or do I just copy/paste some code from the Demo-Site (does it still corresponds to actual BEST PRACTICE ?)
- https://neos.readthedocs.io/en/stable/HowTos/RenderingMenu.html?highlight=menu
- https://neos.github.io/neos/4.0/source-class-Neos.Neos.Fusion.AbstractMenuImplementation.html#18-176

2. **CONTENT**
when I had a layout (grid) and I just wanted to place some characteristic **content** into this sections, is there any tutorial that describe how to just do this basic tasks straight forward. Could be 'first-steps' tutorials ... Do I have to make a whole investigation in code and docs before ...
- https://neos.readthedocs.io/en/stable/HowTos/CreatingContentElement.html

Are there (skilled) developers who might gave up frustrated, because they were already 'blocked' (somehow) during these '**_simplest_**' (basic) **first steps** ... ?

(**if things are clear**, - could they be described understandable and **compact** ?)

**Comment by maxstoyanov** [comment]
I'll close this and make a new actionable issue with a reference to this one.
