### ISSUE TITLE
Neos Fusion: attempt to a global approach / overview ...

### ISSUE THREAD

**Issue by chkoeppel** [neos/documentation#5]
> What is "**Fusion**" ?

- how to **present** the 'topic' to somebody who has never heard of 'Fusion' before ...
- is it the '**central tool**' in Neos CMS ? (analogies, comparisons)
- Googling ... '[Neos CMS Fusion](https://www.google.com/search?client=ubuntu&channel=fs&biw=1682&bih=817&tbm=vid&ei=fFzhW5XXMcbRwQK9xKPADw&q=neos+cms+fusion&oq=neos+cms+fusion&gs_l=psy-ab.3...19013.20043.0.20545.4.4.0.0.0.0.140.494.0j4.4.0....0...1c.1.64.psy-ab..0.2.272...0j0i7i30k1j0i30k1j0i7i5i30k1.0.yRCl9Ilw92o)'
- **why** is Fusion so important ?
- **what** are its global capabilities ?
- **how** to (make) understand the concept ?

Referring to **Overview** of Bastian Heist
- **Neos Fusion**: a **_rendering engine_** for the modern web
        https://speakerdeck.com/beheist/neos-fusion-a-rendering-engine-for-the-modern-web

![fusion _global approach_](https://user-images.githubusercontent.com/20425780/48092349-b3dead00-e20c-11e8-92e6-67e8b3ee1bd6.png)
... _??_ ...

> Some reflections ...

_Harmonizing, standardizing glossaries ??_
- [Content-Modeling_ GLOSSARIES.pdf](https://github.com/neos/documentation/files/2555001/Content-Modeling_.GLOSSARIES.pdf)

_Related topics ??_
- **Web-Components** ?
        https://www.webcomponents.org/introduction
        https://component.kitchen/tutorial
- **AMP** (accelerated mobile pages) ?
        https://discuss.neos.io/t/a-unified-solution-for-amp-html/600
        https://www.ampproject.org/learn/overview/

**Comment by maxstoyanov** [comment]
Currently I don't know how to make actionable tasks out of this so I'll close it for now
