### ISSUE TITLE
How do companies actually handle documentations ?

### ISSUE THREAD

**Issue by chkoeppel** [neos/documentation#6]
**Approaches** to cover “documentation”**
How do companies actually handle documentations ...

**1. Code-Documentation is part of coding and responsibility of the respective coders**
- this documentations are logically versioned
- they focus on the coding logics
- this is normally stays a unidirectional task

**2. “Application documentation” or “User documentation”**
- is more diversificated
- can be versioned
- implies multiple points of view
- covers complementary user and application perspectives
--------------------------------------------------------------------------------------------------------------------
As practically every product has to elaborate documentation, there are uncountable examples of good and bad examples.
**Basically** there are

**1. basic software product documentations**
- frameworks
- packages

**2. application software documentations**
- tools

**3. maintainers, providers, cloud-platforms who deliver documentations**
- hosting
- forums
------------------------------------------------------------------------
In **summary**, the more detached from basic software development, the better the documentation must be organized to control the communication charge over time

**1. Companies want to save support time on long term**
- the scope of customer application is more diversified
- how to redirect the customer to the right doc
- how to provide structured and stable docs-overview
(for search engines too !!)
- the scope of handled problems is more individualized

**2. The providers have to reduce this “communication charge” by transforming it to an “information charge”**
- the more the customers can resolve his problem by just consulting information, the less they will demand for communication
- Q&A sections
- automated “Docs-CMS”
- communication is a personal effort and needs much moderation, even if it’s done in forums, where customers consult customers (this becomes even more emotional)
-------------------------------------------------
**There are very inspiring examples on the web, how to structure, elaborate and moderate “application (or user) documentations”**
- Digital Ocean
https://www.digitalocean.com/docs/
https://www.digitalocean.com/community/tutorials
https://www.digitalocean.com/community/questions

- Ubuntu
https://tutorials.ubuntu.com/

**Comment by maxstoyanov** [comment]
Since we're out of the design phase for our new docs I'll close this
