### ISSUE TITLE
Graphical Overviews (=cheatSheets)

### ISSUE THREAD

**Issue by chkoeppel** [neos/documentation#7]
**Do we need some "graphical" overviews, that would summarize some fusion basics ?**

Roland Schütz did an awesome fundamental work with some videos, concerning fusion basics ...
He shows effectively the correlations and mechanics of Fusion Rendering (definition, mapping, processing)

- https://academy.codeq.at/de/neos-fuer-entwickler/neos-basics
- https://academy.codeq.at/de/neos-fuer-entwickler/understanding-rendering !!!
- https://github.com/code-q-web-factory/Neos-Skeleton/tree/master/DistributionPackages/CodeQ.Site

Would it be useful to reduce some essential topics of this series on some "**cheatSheets**" ?
Here above a **DRAFT example**: 
- **Document**-NodeType 
'integration of a specific footer' with Fusion ...
![fusion rendering - example with footer -- draft](https://user-images.githubusercontent.com/20425780/49385409-a76f4680-f71d-11e8-95d5-634c2a78b8b8.png)
(https://drive.google.com/drive/folders/176_gFUdVjN3TOu0IwBVQd73HeuwdBgNY)
- to facilitate the "the eye catching" of some basic correlations ... for beginners
- to clarify didactics and terms ...  
- to underline and define some **actual Best-Practice** ... (without fluid)

Today, some beginner could become very confused (?), as most examples available on the net (NeosDemoSite, Extensions, Plugins, etc) have very **mixed approaches** (don't they ?)
- fusion with html-templates (Fluid)
- pure fusion rendering, mapping
- AFX
- etc

As an example of the Neos-Blog in 2 variants ...
- https://drive.google.com/file/d/1JhmNMT_j_-xWZ8Z2LeitGpREYCw7Y3-k/view
----------------------
So ... - another one could show a simple typical 'modeling example' (**Plugin**-NodeType ?)  ... in up-to-date-Best-Practice ?
- to animate people to understand content-modeling more methodically ...
- see https://speakerdeck.com/dfeyer/content-modeling-from-theory-to-neos-cms?slide=46 from Dominique Feyer
- how proceed other brands their marketing to "sell" their CMS-product-characteristics ... https://webflow.com/cms
- https://github.com/patriceckhart/NeosRulez.Comments/blob/master/Configuration/NodeTypes.Comments.yaml
----------------
Another one could be a **Content**-NodeType (image-nodeType) like 
- https://github.com/code-q-web-factory/Neos-Skeleton/blob/master/DistributionPackages/CodeQ.Site/Configuration/NodeTypes.Content.Image.yaml
to show with the **Mixin**-nodeType as _superType_ ...
--------
Another one could be a **Constraint**-NodeType ...
- https://github.com/code-q-web-factory/Neos-Skeleton/blob/master/DistributionPackages/CodeQ.Site/Configuration/NodeTypes.Constraint.Content.Restricted.yaml

**Comment by maxstoyanov** [comment]
Currently I don't know how to make actionable tasks out of this so I'll close it for now
