### ISSUE TITLE
Remove the "Feature List"

### ISSUE THREAD

**Issue by beheist** [neos/documentation#8]
Remove https://neos.readthedocs.io/en/stable/GettingStarted/FeatureList.html
we have a better feature list on neos.io by now:
https://www.neos.io/features/feature-list.html

**Comment by rolandschuetz** [comment]
We need to figure out how redirects for readthedocs work.

**Comment by kdambekalns** [comment]
So, who does this? It's in progress, but unassigned…

Redirects need manual work: https://docs.readthedocs.io/en/latest/user-defined-redirects.html

Watch out, though:

> Since we serve documentation in a highly available way, we do not run any logic when we’re serving documentation. This means that redirects will only happen in the case of a 404 File Not Found.

So, trying out redirects before removing things is impossible.

**Comment by beheist** [comment]
I started working on that for now - will add redirects for everything I remove (and hope they work).

**Comment by beheist** [comment]
Added a redirect for the feature list.

**Comment by kdambekalns** [comment]
✅ Works as expected on 3.3, 4.0, 4.1, latest - stable differs, due to something on RTD's side. Solved.

**Comment by kdambekalns** [comment]
Note: "stable" is 4.1.8 and (as any tagged version) will continue to have the removed content.
