### ISSUE TITLE
Move and rewrite "Installation"

### ISSUE THREAD

**Issue by beheist** [neos/documentation#9]
"Installation" should be moved to the top level (Replacing "Getting Started") and should be split into 3 parts (?):
* Simple Installation, using ./flow server:run
* Installation with xampp (possibly on windows)
* Installation with a local web server (more or less the current "Installation") chapter
https://neos.readthedocs.io/en/stable/GettingStarted/Installation.html

**Comment by maxstoyanov** [comment]
We've got several intall guides so I'll close this
